const mongoose = require("mongoose");

const pcSchema = new mongoose.Schema(
  {
    pcId: { type: String, unique: true, required: true }, // autogenerated
    email: String,
    serialNumber: { type: String, required: true, unique: true },

    // Identitas pengguna & aset
    assetNumber: String,
    pic: String,
    userLogin: String,
    isAdmin: { type: Boolean, default: false },
    agentVersion: { type: String, default: null },
    // Status siklus hidup perangkat
    lifecycleStatus: {
      type: String,
      enum: ["in use", "in store", "under repair", "disposal"],
      default: "in use",
    },

    // Lokasi relasional
    location: { type: mongoose.Schema.Types.ObjectId, ref: "Location" },
    type: String,

    // Dinamis
    ipAddress: String,
    status: {
      type: String,
      enum: ["online", "idle", "offline"],
      default: "offline",
    },

    lastActive: Date,

    // Agent settings
    idleTimeout: { type: Number, default: 0 },
    shutdownDelay: { type: Number, default: 0 },

    // Hubungan ke spesifikasi
    spec: { type: mongoose.Schema.Types.ObjectId, ref: "Spec" },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Pc", pcSchema);
